### ISSUE TITLE
Issue when committing multiple files under mac gui tools

### ISSUE THREAD

**Issue by s10wen** [leakypixel/captain-githook#2]
When going to commit a file that has no errors, but there's another file (that you're not committing) but that does contain errors, the error appears and doesn't all the commit of the file with no errors.

**Comment by leakypixel** [comment]
Suspect this is to do with the git snippet that picks up the JS files to check. Investigating.

**Comment by leakypixel** [comment]
This is not a bug in captain-githook, but rather the hooks themselves. I'll look into it there.
